import "./globals.css";

export const metadata = {
  title: "Spicy Harissa",
  description: "Generated by Spicy Harissa",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        {children}
      </body>
    </html>
  );
}
